export const Property = {
  ID: 'mã số',
  NAME: 'tên',
  DESCRIPTION: 'mô tả',
  STATUS: 'trạng thái',
  PRICE: 'giá',
  STOCK: 'số lượng',
  BRAND_NAME: 'thương hiệu',
  CATEGORY_NAME: 'danh mục',
  PRODUCT_THUMNAIL: 'hình ảnh đại diện của sản phẩm',
  PRODUCT: 'sản phẩm',
  IMAGE: 'hình ảnh',
  ORDER: 'đơn hàng',
  TAX: 'thuế',
};
